version: "3"

services:
  app:
    build:
      context: ./../App
      dockerfile: ./../app/app.dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1
