schedules:
  - cron: "0 22 * * 1-5"
    displayName: "6pm Mon - Fri"
    branches:
      include:
        - main
    always: true

trigger: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

stages:
  - stage: Destroy_Apps
    jobs:
      - job: Destroy_sample
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/sp.yml
          - template: templates/execute-tf.yml
            parameters:
              action: "destroy"
              team: "sample"
              env: ""
  - stage: Destroy_Core
    jobs:
      - job: Destroy_Core
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/sp.yml
          - template: templates/execute-tf.yml
            parameters:
              action: "destroy"
              team: "core"
              env: ""
          - template: templates/postCheck.yml
